### ISSUE TITLE
Non-stroke-width links

### ISSUE THREAD

**Issue by emeeks** [d3/d3-sankey#10]
Links should be drawn areas so we can apply fill and stroke like we do with other link based diagrams.

Here's an example:
https://github.com/emeeks/d3.sankey-multipart/blob/master/src/sankey.js#L90

**Comment by mbostock** [comment]
Doing this while preserving the constant width of a link requires computing [Bézier offset curves](https://pomax.github.io/bezierinfo/#offsetting). This is non-trivial, and I don’t think it should fall within the scope of this library. Instead, I recommend using [Bezier.js](https://pomax.github.io/bezierjs/#offset).

**Comment by 015988** [comment]
I wouldn't mind if the links weren't bezier, but straight lines. (The weird ways mine are crossing, that would be a plus, actuall). More than that, non-stroke links would allow for links with different "start" and "end" weights, where it leaves one node with value 10 and reaches another with value 20 for instance.
