### ISSUE TITLE
D3 Sankey customization

### ISSUE THREAD

**Issue by bilmakovskiyruslan** [d3/d3-sankey#101]
D3 Sankey provides limited customization of the Sankey chart (like node|link color (content), width, padding).

Default Sankey chart:
![2](https://user-images.githubusercontent.com/73469420/137757669-b5323c3d-3491-47d4-bf93-3e0632bf956d.png)

But what if I need to change node heights and center the nodes vertically? How I can do that?

My requirements:
![1](https://user-images.githubusercontent.com/73469420/137757719-e6147d19-e9fd-45ab-8baf-74466c997d71.png)

Can anyone help me?

**Comment by simPod** [comment]
I had to fork the sankey lib and wiggle with the model a bit. You cannot do it natively.
