### ISSUE TITLE
Include TypeScript definition?

### ISSUE THREAD

**Issue by aendrew** [d3/d3-sankey#15]
Hi!
I use the DefinitelyTyped D3 TypeScript definitions quite regularly, and I noticed that d3-sankey doesn't have a definition.

GIven the API surface is like half a dozen methods, it probably would be pretty trivial to do. Am happy to do so myself (was hoping to use d3-sankey in the TypeScript chapter of the book I'm working on), but am wondering whether you'd rather include the def with the lib itself or if I should maintain it separately using DefinitelyTyped? Personally I'd prefer to just PR into this repo and include it that way as then TypeScript will just grab the version with the module and not require a separate installation from the `@types` npm org.

**Comment by mbostock** [comment]
Sorry, but I’m not willing to maintain TypeScript definitions, so I suggest submitting them to DefinitelyTyped.

**Comment by aendrew** [comment]
@mbostock Ah, for some reason I thought @xaranke was maintaining this repo. Okay, sounds good — will submit to DT. Thanks for getting back to me so quickly!

**Comment by tomwanzek** [comment]
FYI: See submitted [DefinitelyTyped PR 16051](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16051).

**Comment by aendrew** [comment]
@tomwanzek As always, you sir are a star. 🙌

**Comment by tomwanzek** [comment]
@aendrew Thanks, just providing the gift wrapping for the actual present that is **d3-sankey**
