### ISSUE TITLE
Drag does not work in the example

### ISSUE THREAD

**Issue by espinielli** [d3/d3-sankey#18]
Drag of nodes does not work (the same for the bl.ock mentioned in issue #6 )
Here is what I get in the Chrome Console:
> Uncaught TypeError: Cannot read property 'y' of undefined
>    at SVGGElement.dragmove ((index):138)
>    at e.apply (d3.min.js:2)
>    at b (d3.min.js:1)
>    at Object.l [as mouse] (d3.min.js:1)
>    at r (d3.min.js:1)
>    at d3.min.js:1

The code seems ok and similar to other bl.ocks for d3 v4 sankeys.
The issue stems from the custom built `d3.min.js`.
Substituting 
```html
  <script src="d3.min.js"></script>
```
with

```
  <script src="//d3js.org/d3.v4.min.js"></script>
  <script src="//unpkg.com/d3-sankey@0"></script>
```
fixes everything.

**Comment by adrienfourel** [comment]
Problem is _event_ isn't imported in d3.js 

change following line `import {select} from "d3-selection";` to` import {select, event} from "d3-selection";` then export event and it should be fine.

Be sure to export as explained in this answer from @mbostock : http://stackoverflow.com/a/40048292/3982261

**Comment by mbostock** [comment]
I’ve removed drag interaction from the [energy flow example](https://bl.ocks.org/mbostock/ca9a0bb7ba204d12974bca90acc507c0) for simplicity’s sake.

**Comment by aendrew** [comment]
Please consider adding an example with dragging because currently all the examples accessible with  a legitimate amount of googling point to d3-noob's versions that use an outdated version of the plugin.
