### ISSUE TITLE
Better layout heuristics?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-sankey#33]
We are too aggressive about push nodes towards the center of its source and target neighbors, rather than containing the node within their spans.

**Comment by holgerbrandl** [comment]
Is there a literature reference of layout method, is it 
> Zarate, D. C., Le Bodic, P., Dwyer, T., Gange, G., & Stuckey, P. (2018). Optimal Sankey Diagrams Via Integer Programming (pp. 135–139). Presented at the 2018 IEEE Pacific Visualization Symposium (PacificVis), IEEE. doi:10.1109/pacificvis.2018.00025

? 

I found the the impl at https://github.com/d3/d3-sankey/blob/e4475b1b4f0c4409d052d7e82088f0fff963c184/src/sankey.js#L177 but there's no docs detailing out the source.

**Comment by mbostock** [comment]
I’ve made a number of improvements in recent releases. This issue isn’t particularly actionable, though thanks for the link to the paper, @holgerbrandl! There is a link here:

https://ialab.it.monash.edu/~dwyer/papers/optimal-sankey-diagrams.pdf
