### ISSUE TITLE
export 'min' was not found in 'd3-collection'

### ISSUE THREAD

**Issue by zemirco** [d3/d3-sankey#35]
I just wanted to try the new version with the alignment features (great work :+1: btw) and got the above mentioned error.

At the moment we have at https://github.com/d3/d3-sankey/blob/master/src/align.js#L1

```js
import {min} from "d3-collection";
```

Since `d3-collection` does not have `min` shouldn't it be `d3-array` instead?

```js
import {min} from "d3-array";
```

**Comment by mbostock** [comment]
Oops! Fixed in 0.7.1.
