### ISSUE TITLE
Nodes and links limitation

### ISSUE THREAD

**Issue by fabiomolinar** [d3/d3-sankey#36]
Hello,
I have an application with a fairly high number of **nodes** (107) and **links** (224). Every time I try to draw the diagram, the page freezes and seems never to finish the calculations. When I reduced the number of **nodes** to 10 and **links** to 20, I could draw the chart without problems.

So, my question is, is there a limit of **nodes** and **links** to which this library can be applied? I have waited for more than 2 minutes for the drawing to show up but nothing happens. Should I wait longer (P.S.: _speed is not critical for me_)?

I am using a function to map the `source` and `target` **nodes**. If instead I use the standard approach with indexes, would it be faster?

**Comment by fabiomolinar** [comment]
This is a preview of the links array:

`"links":[{"source":"0","target":"41","value":"2"},{"source":"0","target":"42","value":"4"},{"source":"1","target":"43","value":"14"},{"source":"2","target":"44","value":"21"},{"source":"1","target":"45","value":"14"},{"source":"3","target":"46","value":"22"},{"source":"0","target":"47","value":"2"},{"source":"4","target":"48","value":"18"},{"source":"5","target":"49","value":"26"},{"source":"6","target":"50","value":"33"},{"source":"7","target":"41","value":"8"},{"source":"7","target":"47","value":"2"},{"source":"7","target":"51","value":"5"},{"source":"8","target":"52","value":"2"},{"source":"8","target":"42","value":"4"},{"source":"9","target":"51","value":"5"},{"source":"9","target":"53","value":"2"},{"source":"9","target":"47","value":"2"},{"source":"10","target":"41","value":"2"},{"source":"10","target":"47","value":"2"},{"source":"10","target":"42","value":"4"},{"source":"11","target":"41","value":"2"},{"source":"11","target":"47","value":"2"},{"source":"11","target":"51","value":"5"},{"source":"12","target":"54","value":"5"},{"source":"13","target":"55","value":"6"},{"source":"14","target":"42","value":"6"},{"source":"14","target":"56","value":"5"},{"source":"15","target":"57","value":"4"},{"source":"16","target":"58","value":"24"},{"source":"14","target":"47","value":"4"},{"source":"14","target":"59","value":"4"},{"source":"17","target":"59","value":"4"},{"source":"13","target":"60","value":"2"},{"source":"18","target":"61","value":"4"},{"source":"19","target":"48","value":"8"},{"source":"13","target":"62","value":"2"},{"source":"20","target":"63","value":"4"},{"source":"13","target":"64","value":"5"},{"source":"21","target":"65","value":"4"},{"source":"22","target":"66","value":"6"},{"source":"23","target":"57","value":"8"},{"source":"23","target":"67","value":"8"},{"source":"21","target":"68","value":"4"},{"source":"24","target":"42","value":"12"},{"source":"25","target":"49","value":"2"},{"source":"26","target":"54","value":"5"},{"source":"27","target":"55","value":"6"},{"source":"27","target":"60","value":"2"},{"source":"27","target":"62","value":"2"},{"source":"27","target":"64","value":"5"},{"source":"28","target":"49","value":"2"},{"source":"29","target":"69","value":"5"},{"source":"30","target":"70","value":"6"},{"source":"31","target":"42","value":"6"},{"source":"31","target":"56","value":"5"},{"source":"31","target":"47","value":"4"},{"source":"31","target":"59","value":"4"},{"source":"32","target":"59","value":"4"},{"source":"30","target":"60","value":"2"},{"source":"33","target":"61","value":"4"},{"source":"30","target":"62","value":"2"},{"source":"34","target":"63","value":"4"},{"source":"30","target":"71","value":"5"},{"source":"35","target":"65","value":"4"},{"source":"36","target":"66","value":"6"},{"source":"35","target":"68","value":"4"},{"source":"37","target":"49","value":"2"},{"source":"38","target":"69","value":"5"},{"source":"39","target":"70","value":"6"},{"source":"39","target":"60","value":"2"},{"source":"39","target":"62","value":"2"},{"source":"39","target":"71","value":"5"},{"source":"40","target":"0","value":"1"},{"source":"6","target":"1","value":"1"},{"source":"41","target":"2","value":"2"},{"source":"42","target":"72","value":"7"},{"source":"43","target":"73","value":"7"},{"source":"44","target":"1","value":"7"},{"source":"44","target":"74","value":"7"},{"source":"42","target":"3","value":"6"},{"source":"45","target":"75","value":"6"},{"source":"42","target":"0","value":"1"},{"source":"46","target":"4","value":"2"},{"source":"41","target":"5","value":"5"},{"source":"47","target":"6","value":"9"},{"source":"48","target":"76","value":"13"},{"source":"49","target":"7","value":"2"},{"source":"50","target":"4","value":"1"},{"source":"50","target":"77","value":"2"},{"source":"41","target":"78","value":"3"},{"source":"51","target":"79","value":"3"},{"source":"51","target":"80","value":"3"},{"source":"51","target":"8","value":"1"},{"source":"51","target":"74","value":"1"},{"source":"41","target":"8","value":"1"},{"source":"52","target":"3","value":"1"},{"source":"41","target":"75","value":"1"},{"source":"42","target":"1","value":"1"},{"source":"46","target":"2","value":"1"},{"source":"42","target":"9","value":"1"},{"source":"45","target":"77","value":"1"},{"source":"51","target":"9","value":"1"},{"source":"51","target":"81","value":"1"},{"source":"41","target":"9","value":"1"},{"source":"53","target":"4","value":"1"},{"source":"49","target":"82","value":"1"},{"source":"50","target":"10","value":"1"},{"source":"41","target":"4","value":"1"},{"source":"49","target":"10","value":"1"},{"source":"50","target":"1","value":"1"},{"source":"42","target":"11","value":"1"},{"source":"49","target":"11","value":"1"},{"source":"51","target":"13","value":"1"},{"source":"51","target":"14","value":"1"},{"source":"54","target":"1","value":"1"},{"source":"55","target":"2","value":"1"},{"source":"42","target":"14","value":"2"},{"source":"46","target":"15","value":"2"},{"source":"55","target":"16","value":"1"},{"source":"56","target":"83","value":"2"},{"source":"57","target":"84","value":"6"},{"source":"58","target":"85","value":"6"},{"source":"58","target":"86","value":"2"},{"source":"58","target":"14","value":"1"},{"source":"56","target":"4","value":"4"},{"source":"55","target":"5","value":"2"},{"source":"49","target":"14","value":"2"},{"source":"50","target":"75","value":"4"},{"source":"55","target":"17","value":"2"},{"source":"59","target":"75","value":"4"},{"source":"55","target":"13","value":"1"},{"source":"59","target":"18","value":"2"},{"source":"54","target":"19","value":"2"},{"source":"60","target":"5","value":"4"},{"source":"61","target":"6","value":"4"},{"source":"49","target":"13","value":"1"},{"source":"50","target":"20","value":"2"},{"source":"54","target":"87","value":"1"},{"source":"62","target":"13","value":"1"},{"source":"63","target":"21","value":"2"},{"source":"54","target":"22","value":"2"},{"source":"64","target":"23","value":"2"},{"source":"65","target":"16","value":"4"},{"source":"66","target":"83","value":"4"},{"source":"58","target":"23","value":"4"},{"source":"58","target":"88","value":"4"},{"source":"66","target":"21","value":"2"},{"source":"67","target":"24","value":"4"},{"source":"64","target":"1","value":"2"},{"source":"68","target":"2","value":"2"},{"source":"42","target":"89","value":"2"},{"source":"46","target":"90","value":"2"},{"source":"64","target":"25","value":"1"},{"source":"64","target":"6","value":"2"},{"source":"54","target":"76","value":"2"},{"source":"49","target":"27","value":"2"},{"source":"50","target":"14","value":"1"},{"source":"54","target":"3","value":"1"},{"source":"55","target":"75","value":"1"},{"source":"46","target":"86","value":"2"},{"source":"55","target":"14","value":"1"},{"source":"55","target":"27","value":"1"},{"source":"54","target":"91","value":"1"},{"source":"62","target":"27","value":"1"},{"source":"64","target":"28","value":"1"},{"source":"49","target":"30","value":"2"},{"source":"50","target":"31","value":"2"},{"source":"69","target":"1","value":"1"},{"source":"70","target":"2","value":"1"},{"source":"42","target":"31","value":"2"},{"source":"70","target":"16","value":"1"},{"source":"58","target":"31","value":"1"},{"source":"70","target":"5","value":"2"},{"source":"49","target":"31","value":"2"},{"source":"70","target":"32","value":"2"},{"source":"70","target":"30","value":"1"},{"source":"59","target":"33","value":"2"},{"source":"69","target":"19","value":"2"},{"source":"50","target":"34","value":"2"},{"source":"69","target":"92","value":"2"},{"source":"62","target":"30","value":"1"},{"source":"63","target":"35","value":"2"},{"source":"69","target":"36","value":"2"},{"source":"71","target":"23","value":"2"},{"source":"66","target":"35","value":"2"},{"source":"71","target":"3","value":"2"},{"source":"68","target":"75","value":"2"},{"source":"42","target":"93","value":"2"},{"source":"46","target":"94","value":"2"},{"source":"71","target":"37","value":"1"},{"source":"71","target":"6","value":"2"},{"source":"69","target":"76","value":"2"},{"source":"49","target":"39","value":"2"},{"source":"69","target":"3","value":"1"},{"source":"70","target":"75","value":"1"},{"source":"70","target":"31","value":"1"},{"source":"70","target":"39","value":"1"},{"source":"62","target":"39","value":"1"},{"source":"71","target":"40","value":"1"},{"source":"72","target":"95","value":"7"},{"source":"73","target":"96","value":"7"},{"source":"74","target":"97","value":"8"},{"source":"75","target":"98","value":"19"},{"source":"76","target":"99","value":"17"},{"source":"77","target":"100","value":"3"},{"source":"78","target":"101","value":"3"},{"source":"79","target":"102","value":"3"},{"source":"80","target":"103","value":"3"},{"source":"81","target":"99","value":"1"},{"source":"82","target":"99","value":"1"},{"source":"83","target":"99","value":"6"},{"source":"84","target":"99","value":"6"},{"source":"85","target":"99","value":"6"},{"source":"86","target":"99","value":"4"},{"source":"87","target":"104","value":"1"},{"source":"88","target":"99","value":"4"},{"source":"89","target":"99","value":"2"},{"source":"90","target":"99","value":"2"},{"source":"91","target":"104","value":"1"},{"source":"92","target":"104","value":"2"},{"source":"93","target":"99","value":"2"},{"source":"94","target":"99","value":"2"},{"source":"40","target":"49","value":"1"}]`

**Comment by mbostock** [comment]
You probably have a cycle in the graph; see #1. (If that’s not the case, you can reopen and I will investigate.)

**Comment by fabiomolinar** [comment]
You're probably right @mbostock. I'll review the data and I'll let you know if something.
