### ISSUE TITLE
Specify node and link colors

### ISSUE THREAD

**Issue by jonvitale** [d3/d3-sankey#46]
Would it be possible to add an API function that takes in an associative array which defines keys that represent either the name of a node or some representation of a link, and then specifies color values?

So something like,
```json
"nodeColors": {
   "Nuclear": "#FF0000",
   "Other waste": "#0000FF",
   "default": "#000000"
}
```
Maybe for links, an array of objects:
```json
"linkColors": [
  {"source":"Nuclear", "target":"Nuclear", "color":"#00FF00"},
  {"source":"Nuclear", "target":"Other waste", "color":"#000000"}
]
```
If this is already possible, please let me know.

**Comment by bvoisin** [comment]
You can always set the color when you create the SVG elements : 
```
const node = nodesG.selectAll('.node')
      .data(graphData.nodes)
      .enter().append('g')
      .append('rect')
      .attr('x', d => d.x0)
      .attr('y', d => d.y0)
      .attr('height', d => d.y1 - d.y0)
      .attr('width', d => d.x1 - d.x0)
      .attr('fill', d => nodeColors[d.id]);
```

**Comment by mbostock** [comment]
This library doesn’t do any rendering; it just computes the layout. See this example for some rendering strategies:

https://observablehq.com/@d3/sankey-diagram
