### ISSUE TITLE
[Feature request] searching nodes based on String and numeric id

### ISSUE THREAD

**Issue by JHuiG** [d3/d3-sankey#51]
Correct me if i'm wrong. The current d3-sankey only allows searching nodes based on numeric ID. it will be good if we can search by node name. For example, the JSON file below, we can simply store the links in DB easily.

`{
"nodes":[
{"name":"Barry"},
{"name":"Frodo"},
{"name":"Elvis"},
{"name":"Sarah"},
{"name":"Alice"}
],
"links":[
{"source":"Barry","target":"Elvis","value":2},
{"source":"Frodo","target":"Elvis","value":2},
{"source":"Frodo","target":"Sarah","value":2},
{"source":"Barry","target":"Alice","value":2},
{"source":"Elvis","target":"Sarah","value":2},
{"source":"Elvis","target":"Alice","value":2},
{"source":"Sarah","target":"Alice","value":4}
]}`

Possible modification is to include a find id by string method. at:
`Function find(nodeById, id`)

Cheers.

**Comment by meeple142** [comment]
You can :) https://github.com/d3/d3-sankey#sankey_nodeId
make sure you are using 0.7 or higher
it took me awhile to figure it out
let me know if you have a question

**Comment by mbostock** [comment]
Yep, please use [*sankey*.nodeId](https://github.com/d3/d3-sankey/blob/master/README.md#sankey_nodeId).

**Comment by A-Post** [comment]
Hey there,
I don't understand where I've to do this. Are there some examples ?
