### ISSUE TITLE
Custom rendering for nodes

### ISSUE THREAD

**Issue by holgerbrandl** [d3/d3-sankey#59]
Is it possible to provide a custom node renderer? I'd like to use a heatmap instead of just a colored boxes, such as done in  in http://data.caleydo.org/papers/2010_infovis_matchmaker.pdf  
![image](https://user-images.githubusercontent.com/200952/42632412-603d6eb0-85dd-11e8-9ed1-df9a4eb25c8e.png)

If this feature is not yet available, any pointers to custom node rendering in general would be helpful.

**Comment by mbostock** [comment]
This library doesn’t do any rendering. It just computes the layout of the nodes. So you’re welcome to render the nodes however you like.
