### ISSUE TITLE
Updated example with drag behavior

### ISSUE THREAD

**Issue by syntagmatic** [d3/d3-sankey#6]
Here's the primary example with fixes for the v4 release (like `d3.schemeCategory20`) and `d3-drag` enabled: http://bl.ocks.org/syntagmatic/77c7f7e8802e8824eed473dd065c450b

I pulled out the build system and modified the built version of `d3-sankey` to work with `d3.v4.min.js` to reduce the complexity and number of files in the example codebase.

**Comment by xaranke** [comment]
Sankey is updated, will update the example then close this issue. Thanks for the feedback!
