### ISSUE TITLE
Up to date example/block? 

### ISSUE THREAD

**Issue by JuroUhlar** [d3/d3-sankey#73]
Hi there! 

I am trying to use d3-sankey on a single HTML page visualization, vanilla JS, very straightforward.

But all examples I can find use some old version of the package, for example 
https://www.d3-graph-gallery.com/graph/sankey_basic.html
https://bl.ocks.org/d3noob/06e72deea99e7b4859841f305f63ba85

I want to use the latest version to take advantage of the `sankey.nodeId()` function which doesn't seem to be available in the old version used by all examples. Simpy replacing the d3-sankey to the latest version breaks the example, the API seems to be quite different.

 Is there an up to date example available and I am just missing it? If not, I think it would help a lot. Thanks! :)

**Comment by mbostock** [comment]
The links in the README should take you to the right place.

https://observablehq.com/@d3/sankey-diagram
https://observablehq.com/collection/@d3/d3-sankey
https://observablehq.com/@mbostock/flow-o-matic

**Comment by JuroUhlar** [comment]
Ah, thanks! I think I overlooked it because I was looking for a minimal working example (more suitable for learning purposes), the ones you have seem a little complicated/specialized. If I put something together I'll try to post it as a block. Cheers!

**Comment by curran** [comment]
@JuroUhlar Try these https://blockbuilder.org/search?text=sankey&thumb=true

**Comment by mbostock** [comment]
Or similarly: https://observablehq.com/search?query=sankey
