### ISSUE TITLE
IE 11 issue

### ISSUE THREAD

**Issue by shivasai09** [d3/d3-sankey#77]
Hi,
we are not able to load the d3-sankey in IE11.

could you please let us know what polyfills we need support d3-sankey in IE11.

i believe d3-sankey using some of the api which are not supported by IE11

**Comment by shivasai09** [comment]
ping on this one

**Comment by gordonwoodhull** [comment]
Please see the release notes.

https://github.com/d3/d3-sankey/releases/tag/v0.12.0

**Comment by shivasai09** [comment]
@gordonwoodhull i see that release notes mentioned only `for-of`, will it resolve the issue if i add only plugin for this feature or is it possible that there might be other new es6 features

**Comment by gordonwoodhull** [comment]
It is a language feature and can’t be polyfilled; as the release notes say, you need to stick with the earlier version or transpile.
