### ISSUE TITLE
Host d3-sankey.js somewhere

### ISSUE THREAD

**Issue by syntagmatic** [d3/d3-sankey#8]
Could it be as easy as

```javascript
<script src="https://d3js.org/d3.v4.js"></script>
<script src="https://d3js.org/d3-sankey.v0.js"></script>
```

?

@xaranke @mbostock

**Comment by xaranke** [comment]
@syntagmatic for all of the other d3 packages, @mbostock has hosted them at d3js.org like you mentioned. However, only @mbostock has write permissions to that directory, so unless that changes (either he does it manually each time or allows me write access), I won't be able to change that :(

In the meantime, here's a link to npmcdn: https://npmcdn.com/d3-sankey@0.4.1

**Comment by syntagmatic** [comment]
```javascript
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://npmcdn.com/d3-sankey@0.4.1"></script>
```

👍 

Thanks again! Great work @xaranke on this port to v4.

**Comment by mbostock** [comment]
FYI, npmcdn.com was renamed to unpkg.com.
